# Simple workflow for deploying static content to GitHub Pages
name: Build React Webpage

on:
  # Runs on pushes targeting the release branch
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build
        env:
          PUBLIC_URL: https://lamda-lab.github.io
        run: |
          yarn build
