name: Build React Webpage
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x

      # Enable Corepack for Yarn
      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@3.6.1 --activate

      # Verify Yarn version
      - name: Verify Yarn version
        run: yarn --version

      # Install dependencies without lockfile modification
      - name: Install dependencies
        run: yarn install --immutable-cache

      - name: Build the application
        env:
          PUBLIC_URL: https://lamda-lab.github.io
        run: yarn build
