name: Deploy to GitHub Pages
on:
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: 'deploy'
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: https://lamda-uai.github.io
      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
          
      - name: Setup Yarn
        run: corepack prepare yarn@4.6.0 --activate
          
      - name: Install dependencies
        run: yarn install
        
      - name: Update Browserslist
        run: npx update-browserslist-db@latest
        
      - name: Build
        run: |
          PUBLIC_URL=https://lamda-uai.github.io yarn build
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
