name: Deploy to GitHub Pages
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: 'deploy'
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: https://lamda-uai.github.io
      
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 18.x
          
      - name: Clean and install dependencies
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install --legacy-peer-deps
          npm install --save-dev ajv@^8.0.0 ajv-keywords@^5.0.0
          
      - name: Build
        env:
          CI: false
        run: |
          npm run build
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
