name: Deploy to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: 'deploy'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: https://lamda-lab.github.io

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn 3.6.1
        run: corepack prepare yarn@3.6.1 --activate

      - name: Verify Yarn version
        run: yarn --version

      - name: Install dependencies
        run: yarn install

      - name: Update Browserslist
        run: npx update-browserslist-db@latest

      - name: Build
        run: |
          PUBLIC_URL=https://lamda-lab.github.io yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
